project:
  type: website
  pre-render:
    - src/02-obtain-nws-forecast-data.R
    - src/03-plot-nws-forecast-maps.R
    - src/04-obtain-ndawn-historical-data.R
    - src/05-plot-ndawn-historical-maps.R
    - src/create-gallery-index.R
    - src/generate-gallery.ts
    - src/fix-gallery-image-labels.R

website:
  title: "ND Delta T"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: forecast.qmd
        text: Next 7 Days
      - href: historical.qmd
        text: Past 7 Days
      - href: galleries.qmd
        text: Archive
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

