project:
  type: website
  pre-render:
    - src/create-gallery-index.R
    - src/generate-gallery.ts
    - src/fix-gallery-image-labels.R

website:
  announcement: 
    icon: info-circle
    dismissable: false
    content: "**ATTENTION**. The 2025 growing season has concluded and daily updates of this site have been disabled. This is a static website view as of October 31, 2025."
    type: warning
    position: below-navbar
  google-analytics: "G-9KB6294MHK"
  cookie-consent: true
  title: "ND Delta T"
  navbar:
    background: primary
    foreground: light
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: forecast.qmd
        text: Next 6 Days
      - href: historical.qmd
        text: Past 7 Days
      - href: galleries.qmd
        text: Archive
      - href: about.qmd
        text: About
  page-footer: "[North Dakota State University](https://www.ndsu.edu/equity/about/required_non_discrimination_statement) is an equal opportunity educator and employer. This work is supported by the [U.S. Department of Agriculture’s](https://www.usda.gov/non-discrimination-statement) National Institute of Food and Agriculture."

format:
  html:
    theme: [cosmo, brand]
    css: styles.css
    toc: true
    link-external-newwindow: true
    html-table-processing: none

editor: visual

