project:
  type: website
  pre-render:
    - src/create-gallery-index.R
    - src/generate-gallery.ts
    - src/fix-gallery-image-labels.R

website:
  google-analytics: "G-9KB6294MHK"
  cookie-consent: true
  title: "ND Delta T"
  navbar:
    background: primary
    foreground: light
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: forecast.qmd
        text: Next 6 Days
      - href: historical.qmd
        text: Past 7 Days
      - href: galleries.qmd
        text: Archive
      - href: about.qmd
        text: About

format:
  revealjs:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

