on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install ImageMagick library
        run: sudo apt-get install libmagick++-dev
        
      - name: Install UDUnits library
        run: sudo apt-get install libudunits2-dev

      - name: Install PROJ library
        run: sudo apt-get install libproj-dev proj-data proj-bin

      - name: Install GEOS library
        run: sudo apt-get install libgeos-dev libgeos-c1v5

      - name: Install GDAL library
        run: sudo apt-get install libgdal-dev

      - name: Install SQLite 3
        run: sudo apt-get install sqlite3 libsqlite3-dev 

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
          rtools-version: '44'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          
      - name: Add execute permission to R scripts
        run: git update-index --chmod=+x src/02-obtain-nws-forecast-data.R 

      - name: Run R script - NWS Forecast Data
        run: src/02-obtain-nws-forecast-data.R

     # - name: Run R script - NWS Forecast Maps
       # run: src/03-plot-nws-forecast-maps.R
        
     # - name: Run R script - NDAWN Data 
      #  run: src/04-obtain-ndawn-historical-data.R
        
     # - name: Run R script - NDAWN Maps 
      #  run: src/05-plot-ndawn-historical-maps.R
        
      - name: Push a commit
        run: |
          date > R Scripts
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Data retrival and mapping R scripts"
          git push

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}