on:
  workflow_dispatch:
  schedule:
    - cron: '15 8 * * *'  # Runs daily at 8:15 UTC (2:15 CST)

name: NWS and NDAWN Retrieval and Mapping

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install ImageMagick library
        run: sudo apt-get install libmagick++-dev
        
      - name: Install UDUnits library
        run: sudo apt-get install libudunits2-dev

      - name: Install PROJ library
        run: sudo apt-get install libproj-dev proj-data proj-bin

      - name: Install GEOS library
        run: sudo apt-get install libgeos-dev libgeos-c1v5

      - name: Install GDAL library
        run: sudo apt-get install libgdal-dev

      - name: Install SQLite 3
        run: sudo apt-get install sqlite3 libsqlite3-dev 

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
          rtools-version: '44'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          
      - name: Set execution permissions for R script
        run: chmod +x src/02-obtain-nws-forecast-data.R
  
      - name: Run R script - NWS Forecast Data
        run: Rscript src/02-obtain-nws-forecast-data.R

      - name: Set execution permissions for R script
        run: chmod +x src/03-plot-nws-forecast-maps.R

      - name: Run R script - NWS Forecast Maps
        run: Rscript src/03-plot-nws-forecast-maps.R
        
      - name: Set execution permissions for R script
        run: chmod +x src/04-obtain-ndawn-historical-data.R

      - name: Run R script - NDAWN Data 
        run: Rscript src/04-obtain-ndawn-historical-data.R
        
      - name: Set execution permissions for R script
        run: chmod +x src/05-plot-ndawn-historical-maps.R

      - name: Run R script - NDAWN Maps 
        run: Rscript src/05-plot-ndawn-historical-maps.R
        
      - name: Push a commit
        env:
          ND_DELTA_T_AUTOMATION_TOKEN: ${{secrets.ND_DELTA_T_AUTOMATION_TOKEN}}
        run: |
          git config --global user.name "raproulx"
          git config --global user.email "150395800+raproulx@users.noreply.github.com"
          git add .
          git commit -m "Data retrival and mapping R scripts"
          git push https://${{secrets.ND_DELTA_T_AUTOMATION_TOKEN}}@github.com/${{ github.repository }}.git HEAD:main
